### ISSUE TITLE
landing page neartalent

### ISSUE THREAD

**Issue by gentilmente** [neartalent/landing#1]

**Comment by gentilmente** [comment]
Search for a modern template and adjust it to be online.
something like https://globalrabbits.com/ 
 We already have a neartalent.ar domain.
how take this?

**Comment by Ms2502** [comment]
dejo un .txt con algunos links a templates para ver en la reunion de hoy (4/10)


[links templates.txt](https://github.com/neartalent/landing/files/9708661/links.templates.txt)
