### ISSUE TITLE
Create the corresponding landing page content

### ISSUE THREAD

**Issue by Mateo-Ozino** [neartalent/landing#2]
E.g: Information about us, our projects, etc.

**Comment by gentilmente** [comment]
ok, let's buy some time before we go online.
- need full landing working
- need CDN like Cloudflare to protect the page
- need DNS pointing to neartalent.ar
- need a prod, dev, features branches

ASAP implement "coming soon" page like one of this https://freshdesignweb.com/free-coming-soon-templates/
