### ISSUE TITLE
team photos

### ISSUE THREAD

**Issue by gentilmente** [neartalent/landing#6]

**Comment by gentilmente** [comment]
add your photo as a team member 300x300 px size

**Comment by Mateo-Ozino** [comment]
Here is my photo for the team section of the landing page. Already in 300x300, no need to resize.
![portfolio-pic](https://user-images.githubusercontent.com/99892496/194383029-89e2ef0c-2d65-4541-ae9d-009823f3bd4e.png)

**Comment by gentilmente** [comment]
![camisolix300](https://user-images.githubusercontent.com/993201/194855796-ebbcaa2b-9069-47e4-8de1-8b5d55582217.png)

**Comment by KarenLettieri** [comment]
![KarenLettieri-TeamPhoto](https://user-images.githubusercontent.com/79416757/195461793-d6265a1d-7a02-457d-89db-2c7a4f85d34d.jpeg)

**Comment by KarenLettieri** [comment]
![Karen Lettieri -TP](https://user-images.githubusercontent.com/79416757/195462223-a8a29a54-b119-4539-bb96-b42145453ee0.png)

**Comment by TomiiPorrini** [comment]
![IMG_20220916_101534__1_-removebg](https://user-images.githubusercontent.com/105433665/195462325-1234961b-dabe-493f-865c-53c6c5c0e5e9.png)
